apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-usuarios
data:
  port: "8001"
  db_host: mysql8:3306
  db_database: ms_usuarios
  db_username: root
  db_password: "123456"
  cursos_url: ms-cursos:8002
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-cursos
data:
  port: "8002"
  db_host: postgres14:5432
  db_database: ms_cursos
  db_username: postgres
  db_password: "123456"
  usuarios_url: ms-usuarios:8001