apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-usuarios
data:
  port: "8001"
  db_host: mysql8:3306
  db_database: ms_usuarios
  db_username: root
  cursos_url: ms-cursos:8002
  ambiente: dev
  application.yaml: |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando ambiente de desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configurando ambiente de producción

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-cursos
data:
  port: "8002"
  db_host: postgres14:5432
  db_database: ms_cursos
  db_username: postgres
  usuarios_url: ms-usuarios:8001