apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres14
  template:
    metadata:
      labels:
        app: postgres14
    spec:
      containers:
        - name: postgres14
          image: postgres:14-alpine
          ports:
            - containerPort: 3306
          env:
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_DB
              value: "ms_cursos"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-postgres
          imagePullPolicy: IfNotPresent
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc