version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ms_usuarios
    volumes:
      - "data-mysql:/var/lib/mysql"
    networks:
      - "spring"
  ms-usuarios:
    container_name: ms-usuarios
    image: dhurrego/usuarios:latest
#    build:
#      context: ./
#      dockerfile: ./ms-usuarios/Dockerfile
    ports:
      - "8001:8001"
#    env_file: ./ms-usuarios/.env
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: ms_usuarios
      DB_USERNAME: root
      DB_PASSWORD: 123456
      CURSOS_URL: ec2-54-145-33-201.compute-1.amazonaws.com:8002
    networks:
      - "spring"
    depends_on:
      - mysql8
    restart: always
volumes:
  data-mysql:
    name: data-mysql
networks:
  spring:
    name: spring