spring:
  application:
    name: ms-usuarios
  profiles:
    active: ${AMBIENTE:dev}
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql8:3306}/${DB_DATABASE:ms_usuarios}?serverTimezone=America/Bogota
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true

server:
  port: ${PORT:8001}

logging:
  file:
    path: /app/logs
  level:
    org:
      hibernate:
        SQL: debug

## CREACION RUTAS HEALTH CON ACTUATOR
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true