spring:
  application:
    name: ms-usuarios
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql8:3306}/${DB_DATABASE:ms_usuarios}?serverTimezone=America/Bogota
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

server:
  port: ${PORT:8001}

logging:
  file:
    path: /app/logs
  level:
    org:
      hibernate:
        SQL: debug

ms-cursos:
  url: ${CURSOS_URL:ms-cursos:8002}