spring:
  application:
    name: ms-cursos
  datasource:
    url: jdbc:postgresql://postgres14:5432/ms_cursos
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8002

logging:
  level:
    org:
      hibernate:
        SQL: debug
